on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
   
    - uses: azure/docker-login@v1
      with:
        login-server: blazingreg.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        email: ${{ secrets.REGISTRY_EMAIL }}
   
    - run: |
        docker build -f ./src/BlazingPizza.Orders/Dockerfile -t blazingreg.azurecr.io/blazingpizzaorders:${{ github.sha }} ./src/
        docker push blazingreg.azurecr.io/blazingpizzaorders:${{ github.sha }}
     
    # Set the target AKS cluster.
    - uses: azure/k8s-actions/aks-set-context@master
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: BlazingPizzaCluster
        resource-group: DevIntersections-Pizza
       
#    - uses: azure/k8s-actions/k8s-create-secret@master
#      with:
#        container-registry-url: blazingreg.azurecr.io
#        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
#        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
#        secret-name: demo-secret

    - uses: azure/k8s-actions/k8s-deploy@master
      with:
        manifests: |
          ./src/k8s/orders.yml
        images: |
          blazingreg.azurecr.io/blazingpizzaorders:${{ github.sha }}
#        imagepullsecrets: |
#          demo-secret
